# Generated by Django 5.1.5 on 2025-01-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('poster_url', models.URLField()),
                ('tmdb_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
