# Generated by Django 5.1.5 on 2025-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
